name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug current folder
        run: |
          pwd
          ls -l

      - name: Show compose file
        run: cat docker-compose.yml

      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker compose up -d --build --force-recreate