name: DevSecops End To End Pipeline

on:
  push:
    branches: [main]

jobs:
  code-quality:
    uses: ./.github/workflows/code_quality.yml

  secrets-scan:
    uses: ./.github/workflows/secrets_scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency_scan.yml
    
  docker-scan:
    uses: ./.github/workflows/docker_lint.yml
    
  build:
    needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  trivy:
    needs: [build]
    uses: ./.github/workflows/image-scan.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: [trivy]
    uses: ./.github/workflows/deploy-to-server.yml
    secrets:
      EC2_SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
      EC2_SSH_USER: ${{ secrets.EC2_SSH_USER }}
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}